name: Build Clay Project (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clone and build lz4
      run: |
        git clone https://github.com/lz4/lz4.git third_party/lz4
        cd third_party/lz4
        make
        cd ../..
        
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build project
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel
      
    - name: Package build artifacts
      run: |
        # 创建时间戳用于文件名
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        # 打包整个 build 目录
        zip -r build_artifacts_$TIMESTAMP.zip build/*
        # 保存文件名供后续步骤使用
        echo "ZIP_FILE=build_artifacts_$TIMESTAMP.zip" >> $GITHUB_ENV
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-artifacts
        path: ${{ env.ZIP_FILE }}
        retention-days: 30
