name: Build Clay Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone and build lz4
      run: |
        git clone https://github.com/lz4/lz4.git third_party/lz4
        cd third_party/lz4
        make
        cd ../..
        
    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build project
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

    # 可选：添加测试步骤（如果项目有测试）
    # - name: Run tests
    #   run: ctest --test-dir build
